### ISSUE TITLE
Catanie data set cache and logged in status are out of sync

### ISSUE THREAD

**Issue by dylanmcreynolds** [SciCatProject/frontend#807] opened 2021-07-23 22:49 UTC
### Summary
If you close the browser without logging out, then reopen the  browser, you will see that you are not logged in, but you can see data sets that are private to the last logged-in user.

### Steps to Reproduce
1. Log into Catanie
2. Close the browser window
3. Re-open the browser window
4. Navigate back to Catanie

Observe that Catanie does not think that you're logged in, but you can see private data sets.

### Expected Behaviour
I am not sure if the expected behavior is that you should continue to be logged in after closing the window (user token stored in localStorage) or not. I suspect the expected behavior is that you would continue to be logged in until you click "Logout". But if this is the expected behavior, then catanie should detect that the user is logged out and not present private datasets.

**Comment by nitrosx** [comment] 2022-03-29 14:12
Just tested and I was not able to reproduce the problem.
I will try to wait a longer time between closing the tab and reopening scicat

**Comment by dylanmcreynolds** [comment] 2022-03-29 16:27
This appears fixed to me, too. Now you stay logged in and see your datasets when you navigate back to frontend (step 4 of my steps above.)

OK by me to close. Thanks for the fix @marcoleorato !

**Comment by nitrosx** [comment] 2022-03-29 19:59
Closing this ticket as the issue appears to be solved and it has been tested by 2 people

**Closed by nitrosx** 2022-03-29 19:59 UTC
Labels: bug
